/* eslint-disable prettier/prettier */
import { Knex } from 'knex';

export async function seed(knex: Knex): Promise<void> {
  // Deletes ALL existing entries
  await knex('classes').del();

  // Inserts seed entries
  await knex('classes').insert([
    {
      class_number: 1,
      class_period: '2023.1',
      id_teacher_fk: 1,
      id_subject_fk: 'CDT1101',
      id_department_fk: 643,
    },
    {
      class_number: 3,
      class_period: '2023.1',
      id_teacher_fk: 1,
      id_subject_fk: 'CDS0007',
      id_department_fk: 640,
    },
    {
      class_number: 4,
      class_period: '2023.1',
      id_teacher_fk: 1,
      id_subject_fk: 'CDS0007',
      id_department_fk: 640,
    },
    {
      class_number: 2,
      class_period: '2023.1',
      id_teacher_fk: 1,
      id_subject_fk: 'CDS0012',
      id_department_fk: 640,
    },
    {
      class_number: 5,
      class_period: '2023.1',
      id_teacher_fk: 1,
      id_subject_fk: 'DAP0096',
      id_department_fk: 351,
    },
    {
      class_number: 6,
      class_period: '2023.1',
      id_teacher_fk: 1,
      id_subject_fk: 'DIN0010',
      id_department_fk: 660,
    },
    {
      class_number: 7,
      class_period: '2023.1',
      id_teacher_fk: 1,
      id_subject_fk: 'DIN0010',
      id_department_fk: 660,
    },
    {
      class_number: 8,
      class_period: '2023.1',
      id_teacher_fk: 1,
      id_subject_fk: 'DIN0010',
      id_department_fk: 660,
    },
    {
      class_number: 9,
      class_period: '2023.1',
      id_teacher_fk: 1,
      id_subject_fk: 'DIN0010',
      id_department_fk: 660,
    },
    {
      class_number: 10,
      class_period: '2023.1',
      id_teacher_fk: 1,
      id_subject_fk: 'DIN0010',
      id_department_fk: 660,
    },
    {
      class_number: 11,
      class_period: '2023.1',
      id_teacher_fk: 1,
      id_subject_fk: 'DIN0010',
      id_department_fk: 660,
    },
    {
      class_number: 12,
      class_period: '2023.1',
      id_teacher_fk: 1,
      id_subject_fk: 'DIN0010',
      id_department_fk: 660,
    },
    {
      class_number: 13,
      class_period: '2023.1',
      id_teacher_fk: 1,
      id_subject_fk: 'DIN0010',
      id_department_fk: 660,
    },
    {
      class_number: 14,
      class_period: '2023.1',
      id_teacher_fk: 1,
      id_subject_fk: 'DIN0010',
      id_department_fk: 660,
    },
    {
      class_number: 15,
      class_period: '2023.1',
      id_teacher_fk: 1,
      id_subject_fk: 'DIN0010',
      id_department_fk: 660,
    },
    {
      class_number: 16,
      class_period: '2023.1',
      id_teacher_fk: 1,
      id_subject_fk: 'DIN0010',
      id_department_fk: 660,
    },
    {
      class_number: 17,
      class_period: '2023.1',
      id_teacher_fk: 1,
      id_subject_fk: 'DIN0010',
      id_department_fk: 660,
    },
    {
      class_number: 18,
      class_period: '2023.1',
      id_teacher_fk: 1,
      id_subject_fk: 'ENM0129',
      id_department_fk: 449,
    },
    {
      class_number: 20,
      class_period: '2023.1',
      id_teacher_fk: 1,
      id_subject_fk: 'ENM0129',
      id_department_fk: 449,
    },
    {
      class_number: 21,
      class_period: '2023.1',
      id_teacher_fk: 1,
      id_subject_fk: 'ENM0129',
      id_department_fk: 449,
    },
    {
      class_number: 19,
      class_period: '2023.1',
      id_teacher_fk: 1,
      id_subject_fk: 'ENM0130',
      id_department_fk: 449,
    },
    {
      class_number: 22,
      class_period: '2023.1',
      id_teacher_fk: 1,
      id_subject_fk: 'ENM0130',
      id_department_fk: 449,
    },
    {
      class_number: 23,
      class_period: '2023.1',
      id_teacher_fk: 1,
      id_subject_fk: 'ENM0130',
      id_department_fk: 449,
    },
    {
      class_number: 24,
      class_period: '2023.1',
      id_teacher_fk: 1,
      id_subject_fk: 'ENM0130',
      id_department_fk: 449,
    },
    {
      class_number: 25,
      class_period: '2023.1',
      id_teacher_fk: 1,
      id_subject_fk: 'MAT0025',
      id_department_fk: 518,
    },
    {
      class_number: 26,
      class_period: '2023.1',
      id_teacher_fk: 1,
      id_subject_fk: 'MAT0025',
      id_department_fk: 518,
    },
    {
      class_number: 27,
      class_period: '2023.1',
      id_teacher_fk: 1,
      id_subject_fk: 'MAT0025',
      id_department_fk: 518,
    },
    {
      class_number: 28,
      class_period: '2023.1',
      id_teacher_fk: 1,
      id_subject_fk: 'ADM0273',
      id_department_fk: 327,
    },
    {
      class_number: 29,
      class_period: '2023.1',
      id_teacher_fk: 1,
      id_subject_fk: 'ADM0273',
      id_department_fk: 327,
    },
    {
      class_number: 30,
      class_period: '2023.1',
      id_teacher_fk: 1,
      id_subject_fk: 'ADM0273',
      id_department_fk: 327,
    },
    {
      class_number: 31,
      class_period: '2023.1',
      id_teacher_fk: 1,
      id_subject_fk: 'ADM0273',
      id_department_fk: 327,
    },
    {
      class_number: 32,
      class_period: '2023.1',
      id_teacher_fk: 1,
      id_subject_fk: 'ADM0273',
      id_department_fk: 327,
    },
    {
      class_number: 33,
      class_period: '2023.1',
      id_teacher_fk: 1,
      id_subject_fk: 'ADM0273',
      id_department_fk: 327,
    },
    {
      class_number: 34,
      class_period: '2023.1',
      id_teacher_fk: 1,
      id_subject_fk: 'ADM0273',
      id_department_fk: 327,
    },
    {
      class_number: 35,
      class_period: '2023.1',
      id_teacher_fk: 1,
      id_subject_fk: 'ADM0273',
      id_department_fk: 327,
    },
    {
      class_number: 36,
      class_period: '2023.1',
      id_teacher_fk: 1,
      id_subject_fk: 'ADM0273',
      id_department_fk: 327,
    },
    {
      class_number: 37,
      class_period: '2023.1',
      id_teacher_fk: 1,
      id_subject_fk: 'ADM0273',
      id_department_fk: 327,
    },
    {
      class_number: 38,
      class_period: '2023.1',
      id_teacher_fk: 1,
      id_subject_fk: 'ADM0273',
      id_department_fk: 327,
    },
    {
      class_number: 39,
      class_period: '2023.1',
      id_teacher_fk: 1,
      id_subject_fk: 'ADM0273',
      id_department_fk: 327,
    },
    {
      class_number: 40,
      class_period: '2023.1',
      id_teacher_fk: 1,
      id_subject_fk: 'ADM0273',
      id_department_fk: 327,
    },
    {
      class_number: 41,
      class_period: '2023.1',
      id_teacher_fk: 1,
      id_subject_fk: 'ADM0273',
      id_department_fk: 327,
    },
    {
      class_number: 42,
      class_period: '2023.1',
      id_teacher_fk: 1,
      id_subject_fk: 'ADM0273',
      id_department_fk: 327,
    },
    {
      class_number: 43,
      class_period: '2023.1',
      id_teacher_fk: 1,
      id_subject_fk: 'ADM0273',
      id_department_fk: 327,
    },
    {
      class_number: 44,
      class_period: '2023.1',
      id_teacher_fk: 1,
      id_subject_fk: 'ADM0273',
      id_department_fk: 327,
    },
    {
      class_number: 45,
      class_period: '2023.1',
      id_teacher_fk: 1,
      id_subject_fk: 'ADM0273',
      id_department_fk: 327,
    },
    {
      class_number: 46,
      class_period: '2023.1',
      id_teacher_fk: 1,
      id_subject_fk: 'ADM0273',
      id_department_fk: 327,
    },
    {
      class_number: 47,
      class_period: '2023.1',
      id_teacher_fk: 1,
      id_subject_fk: 'ADM0273',
      id_department_fk: 327,
    },
    {
      class_number: 48,
      class_period: '2023.1',
      id_teacher_fk: 1,
      id_subject_fk: 'ADM0273',
      id_department_fk: 327,
    },
    {
      class_number: 50,
      class_period: '2023.1',
      id_teacher_fk: 1,
      id_subject_fk: 'ADM0273',
      id_department_fk: 327,
    },
    {
      class_number: 51,
      class_period: '2023.1',
      id_teacher_fk: 1,
      id_subject_fk: 'ADM0273',
      id_department_fk: 327,
    },
    {
      class_number: 52,
      class_period: '2023.1',
      id_teacher_fk: 1,
      id_subject_fk: 'ADM0273',
      id_department_fk: 327,
    },
    {
      class_number: 49,
      class_period: '2023.1',
      id_teacher_fk: 1,
      id_subject_fk: 'ADM0297',
      id_department_fk: 327,
    },
    {
      class_number: 53,
      class_period: '2023.1',
      id_teacher_fk: 1,
      id_subject_fk: 'ADM0297',
      id_department_fk: 327,
    },
    {
      class_number: 54,
      class_period: '2023.1',
      id_teacher_fk: 1,
      id_subject_fk: 'ADM0297',
      id_department_fk: 327,
    },
    {
      class_number: 55,
      class_period: '2023.1',
      id_teacher_fk: 1,
      id_subject_fk: 'ADM0297',
      id_department_fk: 327,
    },
    {
      class_number: 56,
      class_period: '2023.1',
      id_teacher_fk: 1,
      id_subject_fk: 'ADM0297',
      id_department_fk: 327,
    },
    {
      class_number: 57,
      class_period: '2023.1',
      id_teacher_fk: 1,
      id_subject_fk: 'ADM0297',
      id_department_fk: 327,
    },
    {
      class_number: 58,
      class_period: '2023.1',
      id_teacher_fk: 1,
      id_subject_fk: 'ADM0297',
      id_department_fk: 327,
    },
    {
      class_number: 59,
      class_period: '2023.1',
      id_teacher_fk: 1,
      id_subject_fk: 'PRO0001',
      id_department_fk: 360,
    },
    {
      class_number: 60,
      class_period: '2023.1',
      id_teacher_fk: 1,
      id_subject_fk: 'PRO0001',
      id_department_fk: 360,
    },
    {
      class_number: 61,
      class_period: '2023.1',
      id_teacher_fk: 1,
      id_subject_fk: 'PRO0001',
      id_department_fk: 360,
    },
    {
      class_number: 62,
      class_period: '2023.1',
      id_teacher_fk: 1,
      id_subject_fk: 'PRO0001',
      id_department_fk: 360,
    },
    {
      class_number: 63,
      class_period: '2023.1',
      id_teacher_fk: 1,
      id_subject_fk: 'PRO0001',
      id_department_fk: 360,
    },
    {
      class_number: 64,
      class_period: '2023.1',
      id_teacher_fk: 1,
      id_subject_fk: 'PRO0001',
      id_department_fk: 360,
    },
    {
      class_number: 65,
      class_period: '2023.1',
      id_teacher_fk: 1,
      id_subject_fk: 'PRO0001',
      id_department_fk: 360,
    },
    {
      class_number: 66,
      class_period: '2023.1',
      id_teacher_fk: 1,
      id_subject_fk: 'PRO0001',
      id_department_fk: 360,
    },
    {
      class_number: 67,
      class_period: '2023.1',
      id_teacher_fk: 1,
      id_subject_fk: 'PRO0001',
      id_department_fk: 360,
    },
    {
      class_number: 68,
      class_period: '2023.1',
      id_teacher_fk: 1,
      id_subject_fk: 'PRO0001',
      id_department_fk: 360,
    },
    {
      class_number: 69,
      class_period: '2023.1',
      id_teacher_fk: 1,
      id_subject_fk: 'PRO0001',
      id_department_fk: 360,
    },
    {
      class_number: 70,
      class_period: '2023.1',
      id_teacher_fk: 1,
      id_subject_fk: 'PRO0001',
      id_department_fk: 360,
    },
    {
      class_number: 71,
      class_period: '2023.1',
      id_teacher_fk: 1,
      id_subject_fk: 'PRO0001',
      id_department_fk: 360,
    },
    {
      class_number: 72,
      class_period: '2023.1',
      id_teacher_fk: 1,
      id_subject_fk: 'PRO0001',
      id_department_fk: 360,
    },
    {
      class_number: 73,
      class_period: '2023.1',
      id_teacher_fk: 1,
      id_subject_fk: 'PRO0001',
      id_department_fk: 360,
    },
    {
      class_number: 74,
      class_period: '2023.1',
      id_teacher_fk: 1,
      id_subject_fk: 'PRO0001',
      id_department_fk: 360,
    },
    {
      class_number: 75,
      class_period: '2023.1',
      id_teacher_fk: 1,
      id_subject_fk: 'PRO0001',
      id_department_fk: 360,
    },
    {
      class_number: 76,
      class_period: '2023.1',
      id_teacher_fk: 1,
      id_subject_fk: 'PRO0001',
      id_department_fk: 360,
    },
    {
      class_number: 77,
      class_period: '2023.1',
      id_teacher_fk: 1,
      id_subject_fk: 'PRO0001',
      id_department_fk: 360,
    },
    {
      class_number: 78,
      class_period: '2023.1',
      id_teacher_fk: 1,
      id_subject_fk: 'PRO0001',
      id_department_fk: 360,
    },
    {
      class_number: 79,
      class_period: '2023.1',
      id_teacher_fk: 1,
      id_subject_fk: 'PRO0001',
      id_department_fk: 360,
    },
    {
      class_number: 80,
      class_period: '2023.1',
      id_teacher_fk: 1,
      id_subject_fk: 'PRO0001',
      id_department_fk: 360,
    },
    {
      class_number: 81,
      class_period: '2023.1',
      id_teacher_fk: 1,
      id_subject_fk: 'PRO0001',
      id_department_fk: 360,
    },
    {
      class_number: 82,
      class_period: '2023.1',
      id_teacher_fk: 1,
      id_subject_fk: 'PRO0001',
      id_department_fk: 360,
    },
    {
      class_number: 83,
      class_period: '2023.1',
      id_teacher_fk: 1,
      id_subject_fk: 'PRO0001',
      id_department_fk: 360,
    },
    {
      class_number: 84,
      class_period: '2023.1',
      id_teacher_fk: 1,
      id_subject_fk: 'PRO0001',
      id_department_fk: 360,
    },
    {
      class_number: 85,
      class_period: '2023.1',
      id_teacher_fk: 1,
      id_subject_fk: 'PRO0001',
      id_department_fk: 360,
    },
    {
      class_number: 100,
      class_period: '2023.1',
      id_teacher_fk: 1,
      id_subject_fk: 'TAU0012',
      id_department_fk: 362,
    },
    {
      class_number: 101,
      class_period: '2023.1',
      id_teacher_fk: 1,
      id_subject_fk: 'TAU0012',
      id_department_fk: 362,
    },
    {
      class_number: 102,
      class_period: '2023.1',
      id_teacher_fk: 1,
      id_subject_fk: 'TAU0012',
      id_department_fk: 362,
    },
    {
      class_number: 86,
      class_period: '2023.1',
      id_teacher_fk: 1,
      id_subject_fk: 'TAU0012',
      id_department_fk: 362,
    },
    {
      class_number: 87,
      class_period: '2023.1',
      id_teacher_fk: 1,
      id_subject_fk: 'TAU0012',
      id_department_fk: 362,
    },
    {
      class_number: 88,
      class_period: '2023.1',
      id_teacher_fk: 1,
      id_subject_fk: 'TAU0012',
      id_department_fk: 362,
    },
    {
      class_number: 89,
      class_period: '2023.1',
      id_teacher_fk: 1,
      id_subject_fk: 'TAU0012',
      id_department_fk: 362,
    },
    {
      class_number: 90,
      class_period: '2023.1',
      id_teacher_fk: 1,
      id_subject_fk: 'TAU0012',
      id_department_fk: 362,
    },
    {
      class_number: 91,
      class_period: '2023.1',
      id_teacher_fk: 1,
      id_subject_fk: 'TAU0012',
      id_department_fk: 362,
    },
    {
      class_number: 92,
      class_period: '2023.1',
      id_teacher_fk: 1,
      id_subject_fk: 'TAU0012',
      id_department_fk: 362,
    },
  ]);
}
